// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FognitiveServices.Vision.TestClient")>]
[<assembly: AssemblyProductAttribute("FognitiveServices")>]
[<assembly: AssemblyDescriptionAttribute("An F# wrapper around the Azure Cognitive Services APIs.")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FognitiveServices.Vision.TestClient"
    let [<Literal>] AssemblyProduct = "FognitiveServices"
    let [<Literal>] AssemblyDescription = "An F# wrapper around the Azure Cognitive Services APIs."
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
