// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FognitiveServices.Text")>]
[<assembly: AssemblyProductAttribute("FognitiveServices")>]
[<assembly: AssemblyDescriptionAttribute("An F# wrapper around the Azure Cognitive Services APIs.")>]
[<assembly: AssemblyVersionAttribute("1.0.1")>]
[<assembly: AssemblyFileVersionAttribute("1.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FognitiveServices.Text"
    let [<Literal>] AssemblyProduct = "FognitiveServices"
    let [<Literal>] AssemblyDescription = "An F# wrapper around the Azure Cognitive Services APIs."
    let [<Literal>] AssemblyVersion = "1.0.1"
    let [<Literal>] AssemblyFileVersion = "1.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
